-- SEC-M-04: Remove the PostgreSQL column default from AuditLog.id.
--
-- Rationale: every db.auditLog.create() call in application code already passes
-- `id: uuidv7()` explicitly (time-sortable, forensic-ordering-friendly).
-- The schema-level default (uuid() = UUIDv4, random) was a safety net that:
--   a) silently accepted callers that forgot to supply an id, and
--   b) produced non-time-sortable ids if ever triggered.
--
-- Dropping the DB default enforces that ALL callers provide the id explicitly.
-- If a caller omits `id`, Prisma will throw a runtime error rather than silently
-- generating a non-sortable v4 UUID.
--
-- No data is modified; existing rows are unaffected.
ALTER TABLE "AuditLog" ALTER COLUMN "id" DROP DEFAULT;
