-- prisma/migrations/20260327100000_conditional_heartbeat_index_t1_2/migration.sql
-- DoD T1.2: Replace the broad last_heartbeat index with a conditional (partial) index
-- that only covers RUNNING nodes. This halves index size and makes orphan-detection
-- queries (WHERE status='RUNNING' AND last_heartbeat < now - threshold) index-only scans.
--
-- PostgreSQL partial index syntax:  CREATE INDEX ... WHERE condition
-- (Prisma does not generate partial indices directly; managed here as raw SQL.)

-- Drop the broad index generated by @@index([last_heartbeat]) in schema.prisma.
-- The index name follows Prisma's convention: "Node_last_heartbeat_idx".
DROP INDEX IF EXISTS "Node_last_heartbeat_idx";

-- Recreate as a partial index covering only RUNNING nodes.
-- Orphan detection: WHERE status = 'RUNNING' AND last_heartbeat < :threshold
CREATE INDEX IF NOT EXISTS "Node_last_heartbeat_running_idx"
  ON "Node" ("last_heartbeat")
  WHERE "status" = 'RUNNING';
