// lib/agents/python-executor.ts
// PythonExecutor — executes Python code inside a Pyodide (WASM) sandbox.
//
// Security model:
//   - Pyodide runs CPython compiled to WebAssembly; no real subprocess access.
//   - __builtins__.__import__ is replaced with a safe version that blocks a
//     list of dangerous modules (os, socket, urllib, ctypes, multiprocessing, …).
//   - Execution runs in a dedicated worker_threads Worker so the main thread can
//     call worker.terminate() on timeout — hard-killing the WASM execution.
//   - resourceLimits.maxOldGenerationSizeMb caps the Worker's heap at 256 MB.
//   - stdout + stderr are captured via Pyodide's setStdout/setStderr hooks and
//     truncated to MAX_OUTPUT_CHARS (50 000 chars) to prevent log flooding.
//
// This is NOT a Firecracker/gVisor-level sandbox. For trusted single-tenant
// deployments (self-hosted Harmoven) this is the recommended approach.
// For strict multi-tenant, add a Docker container per execution layer on top.

import { Worker } from 'worker_threads'
import { resolve } from 'path'

// ─── Constants ────────────────────────────────────────────────────────────────

const DEFAULT_TIMEOUT_MS  = 30_000
const MAX_TIMEOUT_MS      = 120_000
const MEMORY_LIMIT_MB     = 256
const MAX_OUTPUT_CHARS    = 50_000
const MAX_CODE_BYTES      = 100_000  // 100 KB code size limit
const MAX_PACKAGES        = 20
// Safe PyPI package name: alphanumeric, dots, hyphens, underscores; optional ==X.Y.Z specifier.
const PKG_NAME_RE         = /^[a-zA-Z0-9][a-zA-Z0-9._-]*(==?[0-9][a-zA-Z0-9._*-]*)?$/

// WORKER_PATH uses process.cwd() (= project root) rather than __dirname.
// In Next.js, server-side code is compiled into .next/server/chunks/, so
// __dirname resolves to .next/server/ — not lib/agents/ — causing a
// "Cannot find module" error at Worker spawn time.
//
// NOTE: do NOT use require.resolve('pyodide') here. During the Next.js/webpack
// build, require.resolve() is intercepted and replaced with a numeric internal
// module ID (e.g. 54902). The worker receives that number and Node.js throws
// "The id argument must be of type string". The worker .cjs resolves pyodide
// via its own require('pyodide') call — no path needed from the parent.
const WORKER_PATH = resolve(process.cwd(), 'lib/agents/python-executor.worker.cjs')

// ─── Types ────────────────────────────────────────────────────────────────────

export interface PythonExecutorInput {
  /** Python source code to execute (max 100 KB). */
  code: string
  /**
   * Maximum wall-clock execution time in milliseconds.
   * Capped at MAX_TIMEOUT_MS (120 s). Defaults to DEFAULT_TIMEOUT_MS (30 s).
   * Note: package installation time counts towards this limit.
   */
  timeout_ms?: number
  /**
   * PyPI packages to install via micropip before execution.
   *
   * **If omitted or empty (default):** third-party imports are auto-detected from
   * the code's `import` statements using Python's `ast` module, and any name that
   * is not part of the stdlib or already loaded is installed automatically.
   * This is the normal mode when the code is generated by a WRITER node.
   *
   * **If provided:** only those exact packages are installed (auto-detect is skipped).
   * Use this when the import name differs from the PyPI package name:
   * e.g. `import cv2` requires `packages: ['opencv-python']`.
   *
   * Max 20 entries. Names must match `^[a-zA-Z0-9][a-zA-Z0-9._-]*(==?X.Y.Z)?$`.
   */
  packages?: string[]
}

export interface PythonExecutorOutput {
  /** Content written to stdout during execution. */
  stdout: string
  /** Content written to stderr during execution. */
  stderr: string
  /** 0 = success, 1 = Python exception or blocked import. */
  exit_code: 0 | 1
  /** Wall-clock time from Worker spawn to completion (includes Pyodide startup ~2-3 s). */
  duration_ms: number
  /** True when stdout + stderr was truncated to MAX_OUTPUT_CHARS. */
  truncated: boolean
  /** The Python exception message if exit_code = 1, else null. */
  error: string | null
  /** Files generated by the Python script, ready for DB persist. */
  files: ArtifactRef[]
  /**
   * Files that were written by the script but could not be collected:
   * - unknown_ext: extension not in the allowed MIME list
   * - too_large: individual file exceeds 10 MB
   * - total_exceeded: run-level 50 MB budget exhausted
   */
  skipped_files: Array<{ name: string; reason: 'unknown_ext' | 'too_large' | 'total_exceeded' }>
}

export interface ArtifactRef {
  /** Filename, sanitised, e.g. "report.xlsx" */
  name: string
  /** MIME type from whitelist */
  mime: string
  /** File size in bytes */
  sizeBytes: number
  /** Raw binary content (transferred from worker, zero-copy) */
  buffer: ArrayBuffer
}

// Internal message type from worker
interface WorkerResult {
  ok: boolean
  stdout: string
  stderr: string
  error: string | null
  files: Array<{ name: string; mime: string; sizeBytes: number; buffer: ArrayBuffer }>
  skipped_files?: Array<{ name: string; reason: string }>
}

// ─── Pre-execution sanitizer ─────────────────────────────────────────────────

/**
 * Strip leading zeros from decimal integer literals that Python 3 rejects.
 * e.g. `09` → `9`, `007` → `7`, `01` → `1`, `datetime.time(09, 30)` → `datetime.time(9, 30)`.
 *
 * Strategy: split the code on string literals and # comments (captured), then apply
 * the fix only to code-context segments so string contents are not altered.
 */
function fixLeadingZeroIntegers(code: string): string {
  // Tokenize: match string literals (with r/b/f/u prefixes, triple or single quotes)
  // and # comments; everything between matches is code.
  const nonCodeRe =
    /((?:[rRbBfFuU]{1,2})?(?:"""[\s\S]*?"""|'''[\s\S]*?'''|"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')|#[^\n]*)/g
  const parts = code.split(nonCodeRe)
  return parts
    .map((part, idx) => {
      // split() with a capturing group: even indices = code, odd = matched non-code
      if (idx % 2 !== 0) return part
      // Fix 0-prefixed decimal integers: `0+([1-9][0-9]*)` → `$1`
      // Lookbehind prevents matching digits inside larger numbers (e.g. `10` stays `10`).
      // Negative lookahead prevents altering 0x/0o/0b/0. literals.
      return part.replace(
        /(?<![0-9.])0+([1-9][0-9]*)(?![.xXoObBaAcCdDeEfF_])/g,
        (_, digits: string) => digits,
      )
    })
    .join('')
}

// ─── Extract clean error message from Pyodide's verbose traceback ────────────

/**
 * Pyodide wraps Python exceptions in multi-line tracebacks.
 * Extract the most useful single-line summary for logging / node error field.
 */
function extractPyError(raw: string | null): string | null {
  if (!raw) return null
  // Find the last "ExceptionType: message" line
  const lines = raw.split('\n').filter(l => l.trim())
  // Skip "Error in sys.excepthook:", traceback noise, and Pyodide help-URL trailers.
  // The full Pyodide micropip error structure is:
  //   ValueError: <actual error>
  //   You can use micropip.install(..., keep_going=True) ...
  //   await pyodide.loadPackage("micropip") in JavaScript
  //   See https://pyodide.org/... for more details.
  // All of lines 2-4 are help text — only line 1 is meaningful.
  const useful = lines.filter(l =>
    !l.startsWith('Error in sys.excepthook') &&
    !l.startsWith('Traceback') &&
    !l.trim().startsWith('File ') &&
    !l.trim().startsWith('During handling') &&
    !l.trim().startsWith('See https://') &&
    !l.trim().startsWith('You can use') &&
    !l.trim().startsWith('await pyodide.')
  )
  return useful.at(-1)?.trim() ?? raw.slice(0, 200)
}

// ─── Main executor ────────────────────────────────────────────────────────────

export async function executePython(
  input: PythonExecutorInput,
  signal?: AbortSignal,
): Promise<PythonExecutorOutput> {
  // Input validation
  if (typeof input.code !== 'string') {
    throw new TypeError('code must be a string')
  }
  if (Buffer.byteLength(input.code, 'utf8') > MAX_CODE_BYTES) {
    throw new RangeError(`code exceeds ${MAX_CODE_BYTES / 1000} KB limit`)
  }

  if (input.packages !== undefined) {
    if (!Array.isArray(input.packages)) {
      throw new TypeError('packages must be an array')
    }
    if (input.packages.length > MAX_PACKAGES) {
      throw new RangeError(`packages list exceeds ${MAX_PACKAGES} items`)
    }
    for (const pkg of input.packages) {
      if (typeof pkg !== 'string' || !PKG_NAME_RE.test(pkg)) {
        throw new RangeError(`invalid package name: "${pkg}"`)
      }
    }
  }

  const timeoutMs = Math.min(
    input.timeout_ms ?? DEFAULT_TIMEOUT_MS,
    MAX_TIMEOUT_MS,
  )

  const startMs = Date.now()

  return new Promise<PythonExecutorOutput>((resolve, reject) => {
    let settled = false

    const code = fixLeadingZeroIntegers(input.code)

    const worker = new Worker(WORKER_PATH, {
      workerData: { code, packages: input.packages ?? [] },
      resourceLimits: {
        maxOldGenerationSizeMb: MEMORY_LIMIT_MB,
        maxYoungGenerationSizeMb: 32,
      },
    })

    const teardown = (fn: () => void) => {
      if (settled) return
      settled = true
      // Terminate the worker — kills the WASM thread immediately.
      void worker.terminate()
      fn()
    }

    // Wall-clock timeout
    const timer = setTimeout(() => {
      teardown(() =>
        reject(new Error(`Python execution timed out after ${timeoutMs} ms`)),
      )
    }, timeoutMs)

    // Propagate AbortSignal (e.g. run cancelled by user)
    const onAbort = () => {
      clearTimeout(timer)
      teardown(() => reject(new DOMException('Aborted', 'AbortError')))
    }
    signal?.addEventListener('abort', onAbort, { once: true })

    worker.once('message', (msg: WorkerResult) => {
      clearTimeout(timer)
      signal?.removeEventListener('abort', onAbort)

      let stdout  = msg.stdout  ?? ''
      let stderr  = msg.stderr  ?? ''
      let truncated = false

      // Truncate combined output to prevent log flooding
      if (stdout.length + stderr.length > MAX_OUTPUT_CHARS) {
        stdout    = stdout.slice(0, MAX_OUTPUT_CHARS)
        stderr    = stderr.slice(0, Math.max(0, MAX_OUTPUT_CHARS - stdout.length))
        truncated = true
      }

      teardown(() =>
        resolve({
          stdout,
          stderr,
          exit_code: msg.ok ? 0 : 1,
          duration_ms: Date.now() - startMs,
          truncated,
          error: msg.ok ? null : extractPyError(msg.error),
          files: (msg.files ?? []).map(f => ({
            name:      f.name,
            mime:      f.mime,
            sizeBytes: f.sizeBytes,
            buffer:    f.buffer,
          })),
          skipped_files: (msg.skipped_files ?? []).map(f => ({
            name:   f.name,
            reason: f.reason as 'unknown_ext' | 'too_large' | 'total_exceeded',
          })),
        }),
      )
    })

    worker.once('error', (err) => {
      clearTimeout(timer)
      signal?.removeEventListener('abort', onAbort)
      teardown(() => reject(err))
    })
  })
}
