#!/usr/bin/env python3
# scripts/update-release-pins.py
# Amendment 93 — Three-layer release verification (digest + commit SHA + Cosign).
#
# Called by .github/workflows/release.yml > publish-release-pins job.
# Writes (or updates) the instance/release-pins.yaml file in the config repo.
#
# Usage:
#   python3 scripts/update-release-pins.py \
#     --version "1.2.3"            \
#     --digest  "sha256:abc123..."  \
#     --commit  "a1b2c3d4..."       \
#     --bundle  "<base64-cosign>"   \
#     --file    "path/to/release-pins.yaml"
#
# Output format (release-pins.yaml):
#   releases:
#     "1.2.3":
#       published_at: "2026-03-26T12:00:00Z"
#       commit: "a1b2c3d4..."
#       docker_digest: "sha256:abc123..."
#       cosign_bundle: "<base64>"
#     "1.2.2":
#       ...
#
# The file retains all previous release entries. Entries are ordered newest-first.

import argparse
import datetime
import os
import sys

# ─── YAML writer (avoids third-party dependency) ─────────────────────────────

def _yaml_scalar(value: str, *, multiline_key: bool = False) -> str:
    """Return a safely quoted YAML scalar for a string value."""
    # If value contains newlines, use literal block scalar
    if "\n" in value:
        lines = value.split("\n")
        block = "|\n"
        for line in lines:
            block += f"      {line}\n"
        return block.rstrip("\n")
    # Quote strings that could be interpreted as YAML types
    if value in ("true", "false", "null", "~") or value.startswith("0") or value.startswith("-") or ":" in value or "#" in value or value.startswith("*") or value.startswith("&") or value.startswith("!"):
        escaped = value.replace('"', '\\"')
        return f'"{escaped}"'
    return value


def build_entry(version: str, digest: str, commit: str, bundle: str) -> str:
    """Build a YAML block for one release entry."""
    published_at = datetime.datetime.now(datetime.timezone.utc).strftime(
        "%Y-%m-%dT%H:%M:%SZ"
    )
    indent = "    "  # 4 spaces under "releases:"
    lines = [
        f'  "{version}":',
        f'{indent}published_at: "{published_at}"',
        f'{indent}commit: "{commit}"',
        f'{indent}docker_digest: "{digest}"',
        f'{indent}cosign_bundle: "{bundle}"',
    ]
    return "\n".join(lines) + "\n"


# ─── File read/write ──────────────────────────────────────────────────────────

def read_existing(path: str) -> dict[str, str]:
    """
    Parse release-pins.yaml to extract existing version entries as raw blocks.
    Returns dict mapping version string → raw YAML block (already indented).
    We use a simple line-by-line parser to avoid requiring PyYAML.
    """
    if not os.path.exists(path):
        return {}

    entries: dict[str, str] = {}
    current_version: str | None = None
    current_lines: list[str] = []

    with open(path, encoding="utf-8") as f:
        for line in f:
            stripped = line.rstrip("\n")
            # Top-level version key:  "  "1.2.3":"
            if stripped.startswith('  "') and stripped.endswith(":"):
                if current_version is not None:
                    entries[current_version] = "\n".join(current_lines) + "\n"
                current_version = stripped.strip().rstrip(":").strip('"')
                current_lines = [stripped]
            elif current_version is not None and (stripped.startswith("    ") or stripped == ""):
                current_lines.append(stripped)
            else:
                # Part of the header — skip
                if current_version is not None:
                    entries[current_version] = "\n".join(current_lines) + "\n"
                    current_version = None
                    current_lines = []

    if current_version is not None and current_lines:
        entries[current_version] = "\n".join(current_lines) + "\n"

    return entries


def write_pins(path: str, entries: dict[str, str], new_version: str) -> None:
    """Write the release-pins.yaml file, newest-first order."""
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)

    header = (
        "# release-pins.yaml\n"
        "# Auto-generated by scripts/update-release-pins.py (Amendment 93).\n"
        "# Three-layer release verification: Docker digest + commit SHA + Cosign bundle.\n"
        "# DO NOT EDIT MANUALLY.\n"
        "\n"
        "releases:\n"
    )

    # Sort versions descending (newest first) using simple tuple comparison
    def _ver_key(v: str) -> tuple[int, ...]:
        try:
            return tuple(int(x) for x in v.split("."))
        except ValueError:
            return (0,)

    sorted_versions = sorted(entries.keys(), key=_ver_key, reverse=True)

    with open(path, "w", encoding="utf-8") as f:
        f.write(header)
        for v in sorted_versions:
            f.write(entries[v])


# ─── CLI ─────────────────────────────────────────────────────────────────────

def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Update release-pins.yaml with three-layer verification data."
    )
    parser.add_argument("--version", required=True, help="Semver version (e.g. 1.2.3)")
    parser.add_argument("--digest",  required=True, help="Docker image digest (sha256:...)")
    parser.add_argument("--commit",  required=True, help="Git commit SHA (40 hex chars)")
    parser.add_argument("--bundle",  required=True, help="Base64-encoded Cosign bundle JSON")
    parser.add_argument("--file",    required=True, help="Path to release-pins.yaml to write")
    return parser.parse_args()


def main() -> None:
    args = parse_args()

    # Basic input validation — these values end up in a YAML file written to a repo
    if not args.version.replace(".", "").isdigit():
        print(f"ERROR: --version must be a semver string (got: {args.version!r})", file=sys.stderr)
        sys.exit(1)
    if not args.digest.startswith("sha256:"):
        print(f"ERROR: --digest must start with 'sha256:' (got: {args.digest[:20]!r})", file=sys.stderr)
        sys.exit(1)
    if len(args.commit) < 7 or not all(c in "0123456789abcdefABCDEF" for c in args.commit):
        print(f"ERROR: --commit must be a hex SHA (got: {args.commit[:20]!r})", file=sys.stderr)
        sys.exit(1)

    # Read existing entries
    existing = read_existing(args.file)

    if args.version in existing:
        print(f"WARNING: version {args.version} already in {args.file}, overwriting.", file=sys.stderr)

    # Add/replace the new version entry
    existing[args.version] = build_entry(args.version, args.digest, args.commit, args.bundle)

    # Write back
    write_pins(args.file, existing, args.version)
    print(f"OK: {args.file} updated with version {args.version}")


if __name__ == "__main__":
    main()
